version: 0.2

env:
  variables:
    tag: v1

phases:
  install:
    runtime-versions:
          java: corretto8
    commands:
    - echo installed java
    finally:
      - echo completed install phase
  pre_build:
    commands:
      - echo started pre build phase
      - mvn -version
      - java -version
    finally:
    - echo pre build phase is done
  build:
    commands:
    - echo starting mvn build
    - mvn install
    finally:
    - echo build phase is done
  post_build:
    commands:
    - echo starting post_build phase
    - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 026090544525.dkr.ecr.us-west-1.amazonaws.com
    - docker build -t vsm:$tag .
    - docker tag vsm:$tag 026090544525.dkr.ecr.us-west-1.amazonaws.com/vsm:$tag
    - docker push 026090544525.dkr.ecr.us-west-1.amazonaws.com/vsm:$tag
    - echo Build completed on `date`
artifacts:
  files:
    - target/spring-boot-hello-world-1.0.0-SNAPSHOT.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'